name: Snippet, Completion, Indentation, or Build problem
description: Suggest improvements for one of the default language support files.
title: '[PackageName] Title'
body:

  - type: markdown
    attributes:
      value: |
        Please search existing issues to avoid creating duplicates.
        Also, if you are able, follow the [directions](https://github.com/sublimehq/Packages#installation) to check the latest version of this language highlighting.

        If the problem persists, please begin the issue title with the language in square brackets, e.g. `[PHP] Snippet for echo includes the wrong tab stops`.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        This is what should happen:

        ... (you can drop images here)
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        This is what happened instead:

        ... (you can drop images here)
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      placeholder:  |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
