blank_issues_enabled: false
contact_links:

  - name: Latest Sublime Text Build
    url: https://www.sublimetext.com/dev
    about: Please make sure you have tested against the latest Sublime Text Build (dev channel).

  - name: SublimeHQ Discord
    url: https://discord.gg/D43Pecu
    about: Join the SublimeHQ Discord server.
