blank_issues_enabled: false
contact_links:

  - name: Download Sublime Text
    url: https://www.sublimetext.com/dev
    about: Download the latest Sublime Text Build (dev channel).

  - name: Sublime Text Documentation
    url: https://www.sublimetext.com/docs/index.html
    about: The official documentation for Sublime Text.

  - name: Download Sublime Merge
    url: https://www.sublimemerge.com/dev
    about: Download the latest Sublime Merge Build (dev channel).

  - name: Sublime Merge Documentation
    url: https://www.sublimemerge.com/docs/index.html
    about: The official documentation for Sublime Merge.

  - name: SublimeHQ Discord
    url: https://discord.gg/D43Pecu
    about: Join the SublimeHQ Discord server.
