%YAML 1.2
---
###[ BUILTIN BASH COMMANDS ]###################################################

bind:
  short-options: mqurfx
  short-options-compact: lpsvPSVX

builtin:
  ~

caller:
  ~

colon:
  match: ":"
  allow-end-of-options-token: false
  scope: support.function.colon.shell

command:
  short-options-compact: pVv

cd:
  short-options: LPe@

dot:
  match: "\\."
  allow-end-of-options-token: false
  scope: support.function.dot.shell

enable:
  short-options: af
  short-options-compact: dnps

help:
  short-options-compact: dms

logout:
  ~

mapfile:
  short-options: dnOstuCc

printf:
  short-options: v

read:
  short-options-compact: ers
  short-options: adeinNprstu

readarray:
  short-options-compact: ers
  short-options: adeinNprstu

source:
  allow-end-of-options-token: false
  scope: support.function.dot.shell

type:
  short-options-compact: afptP

ulimit:
  short-options-compact: HSabcdefiklmnpqrstuvxPT

# "unalias" is handled in the syntax def, don't put it here!

eval:
  allow-end-of-options-token: false

exec:
  short-options-compact: cl
  short-options: a

# "exit" is handled as keyword.control.flow in the syntax def, don't put it here!

# "export" is handled as storage.modifier in the syntax def, don't put it here!
# export, readonly, declare, local, typeset

getopts:
  ~

hash:
  short-options: rpl
  short-options-compact: dt

pwd:
  short-options-compact: LP

# "readonly" is handled as storage.modifier in the syntax def, don't put it here!

# "return" is handled as keyword.control.flow in the syntax def, don't put it here!

shift:
  allow-end-of-options-token: false
  allow-numeric-args: true

times:
  ~

trap:
  short-options-compact: lp

umask:
  short-options: pS
  allow-numeric-args: true

# "unset" is handled in the syntax def, don't put it here!

echo:
  short-options-compact: neE

set:
  short-options-compact: abefhkmnptuvxBCEHPT
  short-options: o
  allow-end-of-options-token: true
  allow-short-end-of-options-token: true

source:
  ~

shopt:
  short-options-compact: pqsu
  short-options: o

# These are from
# https://www.gnu.org/software/bash/manual/bash.html#Job-Control-Builtins

bg:
  ~

fg:
  ~

jobs:
  short-options-compact: lnprs
  short-options: x

kill:
  short-options: snlL
  # TODO: -sigspec

wait:
  short-options: "n"

disown:
  short-options-compact: ar
  short-options: h

suspend:
  short-options: f

###[ BUILTIN LINUX COMMANDS ]##################################################

su:
  allow-end-of-options-token: true
  short-options-compact: mp
  short-options: -cls
...
