#!/usr/bin/env python3
"""Generate container-specific Markdown emphasis contexts."""

from dataclasses import dataclass
from pathlib import Path
import re
import sys


SYNTAX_PATH = Path(__file__).with_name("Markdown.sublime-syntax")
GENERATED_START = "###[ GENERATED: CONTAINER EMPHASIS ]#########################################"
GENERATED_END = "###[ END GENERATED: CONTAINER EMPHASIS ]#####################################"
BASE_START = "###[ INLINE: EMPHASIS ]#######################################################"
BASE_END = "###[ INLINE: IMAGES ]#########################################################"
OLD_GENERATED_START = (
    "###[ INLINE: BLOCKQUOTE EMPHASIS ]##############################################"
)


@dataclass(frozen=True)
class Variant:
    prefix: str
    title: str
    termination: str
    with_inlines: bool = False
    common_includes: tuple[str, ...] = ()


VARIANTS = (
    Variant(
        "block-quote",
        "BLOCK QUOTE",
        "{{blockquote_paragraph_end}}",
        True,
        ("block-quote-punctuation-content",),
    ),
    Variant(
        "nested-block-quote",
        "NESTED BLOCK QUOTE",
        "{{blockquote_nested_paragraph_end}}",
        True,
        ("block-quote-nested-punctuation-content",),
    ),
    Variant(
        "list",
        "LIST",
        "{{list_paragraph_end}}|{{list_setext_heading_escape}}",
        True,
    ),
    Variant("footnote", "FOOTNOTE", "{{footnote_paragraph_end}}"),
    Variant(
        "block-quote-footnote",
        "BLOCK QUOTE FOOTNOTE",
        "{{blockquote_footnote_paragraph_end}}",
        common_includes=("block-quote-punctuation-content",),
    ),
    Variant("line", "SINGLE LINE", "$", True),
)


def main() -> None:
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        raise SystemExit("usage: generate_markdown_emphasis.py [--check]")

    syntax = SYNTAX_PATH.read_text(encoding="utf-8")
    generated_syntax = generate_syntax(syntax)
    if check:
        if generated_syntax != syntax:
            raise SystemExit(f"{SYNTAX_PATH} needs regeneration")
        return

    SYNTAX_PATH.write_text(generated_syntax, encoding="utf-8", newline="")


def generate_syntax(syntax: str) -> str:
    template = extract_template(syntax)
    generated = "\n\n".join(generate_variant(template, variant) for variant in VARIANTS)
    notice = "# Generated by Markdown/generate_markdown_emphasis.py; do not edit."
    region = f"{GENERATED_START}\n\n{notice}\n\n{generated}\n\n{GENERATED_END}\n\n"
    return replace_generated_region(syntax, region)


def extract_template(syntax: str) -> str:
    emphasis = syntax.index(BASE_START)
    start = syntax.index("  bold:\n", emphasis)
    end = syntax.index("\n###[", start)
    return syntax[start:end].rstrip()


def generate_variant(template: str, variant: Variant) -> str:
    context_names = re.findall(r"^  ([\w-]+):$", template, re.MULTILINE)
    body = transform_contexts(template, context_names, variant)
    heading = f"###[ GENERATED: {variant.title} EMPHASIS ]"
    heading += "#" * (80 - len(heading))
    prelude = generate_prelude(variant)
    return f"{heading}\n\n{prelude}\n\n{body}"


def generate_prelude(variant: Variant) -> str:
    lines = []
    if variant.with_inlines:
        lines.extend(
            (
                f"  {variant.prefix}-inlines:",
                "    - include: hard-line-breaks",
                f"    - include: {variant.prefix}-emphasis",
                "    - include: inline-common",
                "",
            )
        )
    lines.extend(
        (
            f"  {variant.prefix}-emphasis:",
            f"    - include: {variant.prefix}-bold",
            f"    - include: {variant.prefix}-italic",
            f"    - include: {variant.prefix}-strikethrough",
        )
    )
    return "\n".join(lines)


def transform_contexts(template: str, context_names: list[str], variant: Variant) -> str:
    transformed = template
    for name in sorted(context_names, key=len, reverse=True):
        prefixed = f"{variant.prefix}-{name}"
        transformed = re.sub(
            rf"^(  ){re.escape(name)}(:)$",
            rf"\1{prefixed}\2",
            transformed,
            flags=re.MULTILINE,
        )
        transformed = re.sub(
            rf"^([ ]+(?:- )?)(include|set|push|fail|branch_point): {re.escape(name)}$",
            rf"\1\2: {prefixed}",
            transformed,
            flags=re.MULTILINE,
        )
        transformed = re.sub(
            rf"^([ ]+-) {re.escape(name)}$",
            rf"\1 {prefixed}",
            transformed,
            flags=re.MULTILINE,
        )

    generic_end = "{{emphasis_end}}"
    end_variable = variant.prefix.replace("-", "_") + "_emphasis_end"
    container_end = "{{" + end_variable + "}}"
    transformed = transformed.replace(generic_end, container_end)
    common_includes = "".join(
        f"    - include: {context}\n" for context in variant.common_includes
    )
    transformed = transformed.replace(
        f"  {variant.prefix}-emphasis-common:\n"
        "    - include: paragraph-end\n",
        f"  {variant.prefix}-emphasis-common:\n"
        f"    - match: '{variant.termination}'\n"
        "      pop: 1\n"
        f"{common_includes}",
    )
    return transformed


def replace_generated_region(syntax: str, region: str) -> str:
    if GENERATED_START in syntax:
        start = syntax.index(GENERATED_START)
        end = syntax.index(GENERATED_END, start) + len(GENERATED_END)
        while end < len(syntax) and syntax[end] == "\n":
            end += 1
        return syntax[:start] + region + syntax[end:]

    start = syntax.index(OLD_GENERATED_START)
    end = syntax.index(BASE_END, start)
    return syntax[:start] + region + syntax[end:]


if __name__ == "__main__":
    main()
