<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*#\s*region|^\s*/\*|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>^\s*#\s*endregion|^\s*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>C#</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.using.source.cs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(using)\s+([^ ;]*);</string>
			<key>name</key>
			<string>meta.keyword.using.source.cs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((namespace)\s+([\w.]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.namespace.identifier.source.cs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.namespace.source.cs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.source.cs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.namespace.end.source.cs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.namespace.source.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.namespace.begin.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.namespace.body.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.source.cs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtinTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(bool|byte|sbyte|char|decimal|double|float|int|uint|long|ulong|object|short|ushort|string|void|class|struct|enum|interface)\b</string>
					<key>name</key>
					<string>storage.type.source.cs</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(?=\w?[\w\s]*(?:class|struct|interface|enum)\s+\w+)</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.source.cs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.source.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storage-modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.source.cs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.source.cs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(class|struct|interface|enum)\s+(\w+)</string>
					<key>name</key>
					<string>meta.class.identifier.source.cs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>(?={)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.source.cs</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*,?([A-Za-z_]\w*)\b</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.class.begin.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.class.body.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#method</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage-modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtinTypes</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>///</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.block.documentation.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.source.cs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.source.cs</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null|this|base)\b</string>
					<key>name</key>
					<string>constant.language.source.cs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
					<key>name</key>
					<string>constant.numeric.source.cs</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.cs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@"([^"]|"")*"</string>
					<key>name</key>
					<string>string.quoted.double.literal.source.cs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.source.cs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.source.cs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.cs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.source.cs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.source.cs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|for|foreach|in|do|return|continue|break|switch|case|default|goto|throw|try|catch|finally|lock|yield)\b</string>
					<key>name</key>
					<string>keyword.control.source.cs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(from|where|select|group|into|orderby|join|let|on|equals|by|ascending|descending)\b</string>
					<key>name</key>
					<string>keyword.linq.source.cs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(new|is|as|using|checked|unchecked|typeof|sizeof|override|readonly|stackalloc)\b</string>
					<key>name</key>
					<string>keyword.operator.source.cs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|event|delegate|add|remove|set|get|value)\b</string>
					<key>name</key>
					<string>keyword.other.source.cs</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>meta.method.annotation.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#preprocessor</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#builtinTypes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=\bnew\s+)(?=[\w&lt;].*\s+)(?=[^=]+\()</string>
					<key>end</key>
					<string>(?={|;)</string>
					<key>name</key>
					<string>meta.new-object.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!new)(?=[\w&lt;].*\s+)(?=[^=]+\()</string>
					<key>end</key>
					<string>(})|(?=;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.method.end.source.cs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.method.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storage-modifiers</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([\w.]+)\s*\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.source.cs</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.method.identifier.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parameters</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=\w.*\s+[\w.]+\s*\()</string>
							<key>end</key>
							<string>(?=[\w.]+\s*\()</string>
							<key>name</key>
							<string>meta.method.return-type.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>:\s*(this|base)\s*\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.language.source.cs</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.method.base-call.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.method.begin.source.cs</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.method.body.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#code</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!new)(?=[\w&lt;].*\s+)(?=[^=]+\{)</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.property.end.source.cs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property.source.cs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storage-modifiers</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([\w.]+)\s*(?={)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.source.cs</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={)</string>
							<key>name</key>
							<string>meta.method.identifier.source.cs</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=\w.*\s+[\w.]+\s*\{)</string>
							<key>end</key>
							<string>(?=[\w.]+\s*\{)</string>
							<key>name</key>
							<string>meta.method.return-type.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.property.begin.source.cs</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.method.body.source.cs</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#code</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>method-call</key>
		<dict>
			<key>begin</key>
			<string>([\w$]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.method.source.cs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.method-parameters.begin.source.cs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.method-parameters.end.source.cs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.method-call.source.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.definition.seperator.parameter.source.cs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>begin</key>
			<string>\b(ref|params|out)?\s*\b([\w.\[\]]+)\s+(\w+)\s*(=)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.modifier.source.cs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.generic.source.cs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.source.cs</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.source.cs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(,)|(?=[\)]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.parameter.source.cs</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.region.source.cs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(region)\b(.*)$</string>
					<key>name</key>
					<string>meta.preprocessor.source.cs</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.preprocessor.source.cs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(define)\b\s*(\S*)</string>
					<key>name</key>
					<string>meta.preprocessor.source.cs</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.source.cs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(if|else|elif|endif|define|undef|warning|error|line|pragma|region|endregion)\b</string>
					<key>name</key>
					<string>meta.preprocessor.source.cs</string>
				</dict>
			</array>
		</dict>
		<key>storage-modifiers</key>
		<dict>
			<key>match</key>
			<string>\b(event|delegate|internal|public|protected|private|static|const|new|sealed|abstract|virtual|override|extern|unsafe|readonly|volatile|implicit|explicit|operator)\b</string>
			<key>name</key>
			<string>storage.modifier.source.cs</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cs</string>
	<key>uuid</key>
	<string>1BA75B32-707C-11D9-A928-000D93589AF6</string>
</dict>
</plist>
